### ISSUE TITLE
vvvv client cant connect to service if no project is loaded

### ISSUE THREAD

**Issue by ingolfheinsch** [dis-co/disco#82]
### Description
vvvv client cant connect to service if no project is loaded. Is this behavior as expected?

### HowTo Reproduce

unload project in the browser and try to connect vvvv client

### Expected and actual results

Please provide the expected and actual results.

### Environment information

* Disco Version: 0.1.3
* Member Count: 1
* Type of Client: vvvv

### Related information

* RunTime Version:
* Operating system:

**Comment by krgn** [comment]
Yeah, this is intentional. Part of the reason is that when the client connects, it asks the service for the current state of the application to bootstrap its own internal version of the state. Changing this to support _connect-before-load_ would require making some changes in the client/server protocol to allow for it.
